set(CPACK_PACKAGING_INSTALL_PREFIX /usr)

set(CPACK_PACKAGE_CONTACT "Ilya Andreev <bugdealer@icloud.com>")
set(CPACK_DEB_COMPONENT_INSTALL ON)

set(CPACK_DEBIAN_RUNTIME_PACKAGE_NAME "libtmp${PROJECT_VERSION_MAJOR}")
set(CPACK_DEBIAN_DEVELOPMENT_PACKAGE_NAME "libtmp${PROJECT_VERSION_MAJOR}-dev")
set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)

set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
set(CPACK_DEBIAN_PACKAGE_GENERATE_SHLIBS ON)
set(CPACK_DEBIAN_PACKAGE_GENERATE_SHLIBS_POLICY ">=")
set(CPACK_DEBIAN_DEVELOPMENT_PACKAGE_DEPENDS
    "libstdc++-dev, libtmp${PROJECT_VERSION_MAJOR} (= ${PROJECT_VERSION})")

set(CPACK_DEBIAN_RUNTIME_DESCRIPTION
    "Runtime package"
)
set(CPACK_DEBIAN_DEVELOPMENT_DESCRIPTION
    "Development package"
)

include(CPack)
