---
name: package
on:
  push:
    branches: [package]

jobs:
  package:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: macos-14
          platform: arm64_sonoma
        - os: macos-13
          platform: ventura
        - os: macos-12
          platform: monterey
        - os: ubuntu-20.04
          platform: x86_64_linux
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure CMake
        run: cmake -B ${{ vars.BUILD_DIR }}
      - name: Package
        run: cpack -DCPACK_SYSTEM_NAME=${{ matrix.platform }} -G TGZ
        working-directory: ${{ vars.BUILD_DIR }}
      - name: Check contents
        run: tar -tf tmp*.tar.gz
        working-directory: ${{ vars.BUILD_DIR }}
