---
name: package
"on":
  release:
    types: [released]

jobs:
  package:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-14
            platform: arm64_macos
          - os: macos-12
            platform: x86_64_macos
          - os: ubuntu-20.04
            platform: x86_64_linux
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure
        run: cmake -B ${{ vars.BUILD_DIR }} -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DCPACK_SYSTEM_NAME=${{ matrix.platform }} -DCPACK_PACKAGE_VERSION=${{ github.event.release.tag_name }}
      - name: Build
        run: cmake --build ${{ vars.BUILD_DIR }}
      - name: Package
        run: cpack -G TGZ
        working-directory: ${{ vars.BUILD_DIR }}
      - name: Publish
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ vars.BUILD_DIR }}/tmp-${{ github.event.release.tag_name }}-${{ matrix.platform }}.tar.gz
          asset_name: tmp-${{ github.event.release.tag_name }}-${{ matrix.platform }}.tar.gz
          asset_content_type: application/gzip
