---
name: posix
"on":
  push:
    branches: [main]
  pull_request:

env:
  CXXFLAGS: -fsanitize=address -Werror -Wall -Wextra -Wpedantic
  LDFLAGS: -fsanitize=address

jobs:
  cmake:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
          - macos-13
          - macos-15
    steps:
      - name: Set up `tmpfs` (if supported)
        run: sudo mount tmpfs -t tmpfs -o size=100m /tmp
        if: runner.os == 'Linux'
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure CMake
        run: cmake -B build -DBUILD_SHARED_LIBS=TRUE
      - name: Build tests
        run: cmake --build build
      - name: Run tests
        run: ctest --output-on-failure --test-dir build

  meson:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
          - macos-13
          # - macos-15
    steps:
      - name: Set up `tmpfs` (if supported)
        run: sudo mount tmpfs -t tmpfs -o size=100m /tmp
        if: runner.os == 'Linux'
      - name: Install Meson (Linux native)
        run: sudo apt-get install meson
        if: runner.os == 'Linux'
      - name: Install Meson (Brew)
        run: brew install meson
        if: runner.os == 'macOS'
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure Meson
        run: meson setup build
      - name: Run tests
        run: meson test -C build
