name: Tests
on:
  - push
  - pull_request

env:
  build_dir: ${{ github.workspace }}/build

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-22.04
          - macos-11
          - macos-12
          - macos-13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Select Xcode 15.0 (for macOS 13)
        run:  sudo xcode-select -s "/Applications/Xcode_15.0.app"
        if:   matrix.os == 'macos-13'

      - name: Configure CMake
        run:  cmake -B ${{ env.build_dir }}

      - name: Build tests
        run:  cmake --build ${{ env.build_dir }}

      - name: Run tests
        run:  ctest --build-config
        working-directory: ${{ env.build_dir }}
