---
name: Tests
"on":
  push:
    branches: [main]
  pull_request:

env:
  build_dir: ${{ github.workspace }}/build

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-24.04
          - macos-12
          - macos-14
          - windows-2019
          - windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B ${{ env.build_dir }}

      - name: Build tests
        run: cmake --build ${{ env.build_dir }}

      - name: Run tests
        run: ctest --output-on-failure --test-dir ${{ env.build_dir }}
